//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Url_Detector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Url_Detector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http
        ///https
        ///file
        ///ftp.
        /// </summary>
        internal static string KnownProtocols {
            get {
                return ResourceManager.GetString("KnownProtocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aaa (aaa)
        ///aarp (aarp)
        ///abarth (abarth)
        ///abb (abb)
        ///abbott (abbott)
        ///abbvie (abbvie)
        ///abc (abc)
        ///able (able)
        ///abogado (abogado)
        ///abudhabi (abudhabi)
        ///ac (ac)
        ///academy (academy)
        ///accenture (accenture)
        ///accountant (accountant)
        ///accountants (accountants)
        ///aco (aco)
        ///active (active)
        ///actor (actor)
        ///ad (ad)
        ///adac (adac)
        ///ads (ads)
        ///adult (adult)
        ///ae (ae)
        ///aeg (aeg)
        ///aero (aero)
        ///aetna (aetna)
        ///af (af)
        ///afamilycompany (afamilycompany)
        ///afl (afl)
        ///africa (africa)
        ///ag (ag)
        ///agakhan (agakhan)
        ///agency (agency)
        ///ai (a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KnownTLDs {
            get {
                return ResourceManager.GetString("KnownTLDs", resourceCulture);
            }
        }
    }
}
